name: myapp

services:
  api-students:
    build: ./api-students
    ports:
      - 8001:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://52.90.155.72:8001/students"]
      interval: 5s
      timeout: 10s
      retries: 1
  websimple:
    build: ./websimple
    ports:
      - 8080:80
    depends_on:
      api-students:
        condition: service_healthy
